### PR TITLE
Add backend tests to reward badges

### PR DESCRIPTION
**Pull request by Tirokk**
Only admins can reward badges to users.

Related to issue #204 .

### CODE REVIEW

**Comment by mattwr18** [comment]
it's looking great so far @Tirokk

**Comment by appinteractive** [comment]
Awesome 🤩 @Tirokk

**Comment by Tirokk** [comment]
The Travis Branch build failed with: No container found for backen_1
@appinteractive @roschaefer @mattwr18 @Lulalaby 

If this is fixed close #204

**Comment by mattwr18** [comment]
@Tirokk did all the hard work on this, @roschaefer thanks for your clarification of how `MERGE` works in cypher queries.

Also, thanks to @Kachulio1 and @aonomike for joining me this morning for our Wednesday pairing sessions

**Comment by roschaefer** [comment]
closed in favour of https://github.com/Human-Connection/Human-Connection/pull/223

**Pull request closed without merging**
