### PR TITLE
[🚨 DO NOT MERGE 🚨] [WIP] Discord Integration - Backend

### PR DESCRIPTION
**Pull request by Lulalaby**
**Ref: #237** 

grafik
grafik

Features:

- [x] Profile link
- [x] Post link
- [x] Post excerpt
- [ ] Post image if submitted
- [x] Post timestamp
- [x] Project name
- [x] Project status

### CODE REVIEW

**Comment by Lulalaby** [comment]
TODO:

- [ ] Fix excerpt
- [ ] Let the integration be configured via interface (Nitro-Web)
- [ ] Disable completly on `yarn db:seed`

**Comment by Lulalaby** [comment]
**Ref: [#257](https://github.com/Human-Connection/Nitro-Web/pull/257)**

**Comment by appinteractive** [comment]
This needs to be discussed. We have already a feature for activity pub. Why not using that road? I have a bad feeling to hard wire discord there to be honest. 

Also stuff like deleting and other things have to be considered.

**Comment by Lulalaby** [comment]
@appinteractive it is not the end of the branche 😆 
I'll want to write it first, then exclude and reimport as possible extension.
in the same moment, i want to build a extension panel for the owner.
so you can add activity pub, the discord feeder and other things dymanically

**Comment by roschaefer** [comment]
@Lulalaby I as I told you already, it is very likely that we're not going to merge that PR. I give this early feedback to avoid potential disappointment.

I agree with @appinteractive that using ActivityPub would be a very reasonable choice. @Mastercuber is the expert here.

**Comment by Lulalaby** [comment]
I know..

**Comment by roschaefer** [comment]
@Lulalaby I'm moving all the PRs. We will not merge this one so I hope you don't mind if I close it?

**Pull request closed without merging**
