### PR TITLE
[WIP] Create docker-compose.test.yml with separate volume

### PR DESCRIPTION
**Pull request by mattwr18**
Starting the containers using `docker-compose -f docker-compose.yml -f docker-compose.test.yml up --build` gives this output in the terminal
```
backend_1  | Server ready at http://localhost:4000
neo4j_1    | 2019-02-21 16:15:11.794+0000 INFO  Starting...
neo4j_1    | 2019-02-21 16:15:27.408+0000 INFO  Bolt enabled on 0.0.0.0:7687.
neo4j_1    | 2019-02-21 16:15:31.404+0000 INFO  Started.
neo4j_1    | 2019-02-21 16:15:34.022+0000 INFO  Remote interface available at http://localhost:7474/
```
but when trying to visit http://localhost:7474/ and logging in I am getting this error locally
```
 ServiceUnavailable: WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available to this Neo4j Driver. Please use your browsers development conso...
```
@Wolle @roschaefer could you confirm if this is what you are getting locally as well?

### CODE REVIEW

**Comment by Lulalaby** [comment]
Like this it fails ^^

**Comment by mattwr18** [comment]
not sure if we want to keep this open? 
there is a potential workaround not using docker that @appinteractive shared with @roschaefer... :thinking:

**Comment by appinteractive** [comment]
I can’t confirm that as I still can’t run the docker setup due to system issues. 

Sounds like a CORS error. So do I understand it correctly that you neo4j Browser can’t connect to the database right? Is it accessible on localhost?

**Comment by roschaefer** [comment]
Closing this because I changed the new `docker-compose.*.yml` files a lot in the new [monorepo](https://github.com/Human-Connection/Human-Connection)

**Pull request closed without merging**
